spring.application.name=fitness

spring.datasource.url=jdbc:postgresql://ep-plain-breeze-aq3e0pnr-pooler.c-8.us-east-1.aws.neon.tech/fitness?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uX0oHkVW2BwZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT}
FRONTEND.URL=${FRONTEND_URL}





